module.exports = {
  "ALIVE_IMG": "",
  "FOOT": "Ongeri 💜",
  "PREFIX": ".",
  "AUTO_READ_STATUS": "true",
  "MODE": "public",
  "BOT_NUMBER": "254713145618",
  "OMDB_API_KEY": "76cb7f39",
  "READ_CMD": "false",
  "AUTO_VOICE": "false",
  "ANTI_BAD": "warn",
  "ANTI_BOT": "false",
  "ANTI_CALL": "false",
  "ANTI_LINK": "false",
  "ANTI_PHOTO": "warn",
  "ANTI_STICKER": "warn",
  "ANTI_DELETE": false,
  "DELETEMSGSENDTO": "94742274855",
  "ALWAYS_ONLINE": "false",
  "MOROCCO_BLOCK": "false",
  "OWNER_NAME": "Ongeri 💜",
  "OWNER_NUMBER": "254713175618",
  "AUTO_BIO": "true",
  "AUTO_TYPING": "false",
  "AUTO_RECORDING": "false",
  "WARN_COUNT": "3",
  "AI_MODE": true,
};
